image: atlassian/default-image:4

definitions:
  caches:
    nextcache: .next/cache
    yarn: .yarn/cache
    node: node_modules
  steps:
    - step: &build
        name: "Build | Yarn"
        image: node:18
        caches:
          - node
          - yarn
          - nextcache
        script:
          - echo "Yarn"
          - corepack enable
          - yarn set version classic
          - yarn install --frozen-lockfile
          - yarn build
        artifacts:
          - .next/**
          - node_modules/**
          - public/**
    - step: &package
        name: "Build | Package"
        script:
          - echo "Building package"
          - mkdir deploy
          - cp -R {.ebextensions,Procfile,public,.next/standalone/*,.next/standalone/.next} deploy/
          - cp -R .next/static deploy/.next/
          - cd deploy && zip -r application.zip .ebextensions .next lib node_modules public package.json Procfile server.js
          - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - pipe: atlassian/aws-elasticbeanstalk-deploy:1.1.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: $APPLICATION_NAME
              COMMAND: "upload-only"
              ZIP_FILE: "application.zip"
              S3_BUCKET: $S3_BUCKET
              VERSION_LABEL: "$BITBUCKET_BUILD_NUMBER-deploy-$BITBUCKET_COMMIT_SHORT"
    - step: &deploy
        name: "Deploy | Develop"
        script:
          - echo "Deployment!"
          - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - pipe: atlassian/aws-elasticbeanstalk-deploy:1.1.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: $APPLICATION_NAME
              COMMAND: "deploy-only"
              VERSION_LABEL: "$BITBUCKET_BUILD_NUMBER-deploy-$BITBUCKET_COMMIT_SHORT"
              ENVIRONMENT_NAME: $ENVIRONMENT_NAME
              WAIT: "true"
    - step: &invalidate
        name: "Invalidate Cache"
        script:
          - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $AWS_DISTRIBUTION_ID

pipelines:
  branches:
    staging:
      - stage:
          deployment: staging
          steps:
            - step: *build
            - step: *package
            - step: *deploy
            - step: *invalidate
    main:
      - stage:
          deployment: production
          steps:
            - step: *build
            - step: *package
            - step: *deploy
            - step: *invalidate
