image: atlassian/default-image:4

definitions:
  caches:
    nextcache: .next/cache
    node: node_modules
  steps:
    - step: &build
        name: "Build | Yarn"
        image: node:16
        caches:
          - node
          - nextcache
        script:
          - echo "Yarn"
          - yarn install --frozen-lockfile
          - yarn build
        artifacts:
          - .next/**
          - node_modules/**
          - public/**
    - step: &package
        name: "Build | Package"
        script:
          - echo "Building package"
          - mkdir deploy
          - cp -R {.ebextensions,Procfile,public,.next/standalone/*,.next/standalone/.next} deploy/
          - cp -R .next/static deploy/.next/
          - zip -r application.zip deploy/
          - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: $AWS_APPLICATION_NAME
              COMMAND: "upload-only"
              ZIP_FILE: "application.zip"
              S3_BUCKET: $AWS_S3_BUCKET
              VERSION_LABEL: "develop-$BITBUCKET_BUILD_NUMBER-deploy-$BITBUCKET_COMMIT_SHORT"
    - step: &deploy
        name: "Deploy | Develop"
        script:
          - echo "Deployment!"
          - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: $AWS_APPLICATION_NAME
              COMMAND: "deploy-only"
              VERSION_LABEL: "develop-$BITBUCKET_BUILD_NUMBER-deploy-$BITBUCKET_COMMIT_SHORT"
              ENVIRONMENT_NAME: $AWS_ENV
              WAIT: "true"

pipelines:
  branches:
    develop:
      - stage:
          deployment: develop
          steps:
            - step: *build
            - step: *package
            - step: *deploy
    staging:
      - stage:
          deployment: staging
          steps:
            - step: *build
            - step: *package
            - step: *deploy
    main:
      - stage:
          deployment: production
          steps:
            - step: *build
            - step: *package
            - step: *deploy
